apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vworkspace-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: vworkspacesticky
    nginx.ingress.kubernetes.io/session-cookie-expires: "259200"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "259200"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
spec:
  rules:
  - host: vworkspace.test
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vworkspace-app
            port: 
              number: 80
