apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vworkspace-ingress
spec:
  rules:
  - host: vworkspace.test
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vworkspace-app
            port: 
              number: 80
