
apiVersion: v1
kind: PersistentVolumeClaimList
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: vworkspace-db
    spec:
      storageClassName: gluster-sc
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
    

