Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "config-proxy.sh"
  config.vm.provision "shell", path: "install-gluster.sh"
  config.proxy.enabled = false

  config.vm.define "alma-kubeworker1" do |worker1|
    worker1.vm.box = "almalinux/8"
    worker1.vm.network "private_network", ip:"192.168.0.4", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
    worker1.vm.provider "virtualbox" do |d|
      d.cpus = 4
      d.memory = 4096
    end
    worker1.vm.provision "shell", inline: "hostnamectl set-hostname alma-kubeworker1"
    worker1.vm.provision "shell", path: "install-kubeadm.sh"
    worker1.vm.disk :disk, size: "50GB", name: "kubeworker1-gluster"
  end

  config.vm.define "alma-kubeworker2" do |worker2|
    worker2.vm.box = "almalinux/8"
    worker2.vm.network "private_network", ip:"192.168.0.5", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
    worker2.vm.provider "virtualbox" do |d|
      d.cpus = 4
      d.memory = 4096
    end
    worker2.vm.provision "shell", inline: "hostnamectl set-hostname alma-kubeworker2"
    worker2.vm.provision "shell", path: "install-kubeadm.sh"
    worker2.vm.disk :disk, size: "50GB", name: "kubeworker2-gluster"
  end

  # config.vm.define "alma-ansiblemaster" do |ansiblemaster|
  #   ansiblemaster.vm.box = "almalinux/8"
  #   ansiblemaster.vm.network "private_network", ip:"192.168.0.2", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
  #   ansiblemaster.vm.provider "virtualbox" do |d|
  #     d.cpus = 2
  #     d.memory = 2048
  #   end
  #   ansiblemaster.vm.disk :disk, size: "10GB", name: "ansible-gluster"
  #   ansiblemaster.vm.provision "shell", inline: "hostnamectl set-hostname alma-ansiblemaster"
  #   ansiblemaster.vm.provision "shell", path: "install-ansible.sh", privileged: false
  # end

  config.vm.define "alma-kubemaster" do |master|
    master.vm.box = "almalinux/8"
    master.vm.network "private_network", ip:"192.168.0.3", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
    master.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 4096
    end
    master.vm.provision "shell", inline: "hostnamectl set-hostname alma-kubemaster"
    master.vm.provision "shell", path: "install-kubeadm.sh"
    master.vm.provision "shell", path: "config-gluster.sh"
    master.vm.disk :disk, size: "50GB", name: "kubemaster-gluster"
  end
end