apiVersion: v1
kind: Service
metadata:
  name: vworkspace-app
  labels:
    app: vworkspace
    role: app
spec:
  #type: NodePort
  selector:
    app: vworkspace
    role: app
  ports:
    - 
      port: 80
      targetPort: 80
      #nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vworkspace-app
  labels:
    app: vworkspace
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vworkspace
      role: app
  template:
    metadata:
      name: vworkspace-app
      labels:
        app: vworkspace
        role: app
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:stable
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: 'test123'
            - name: MYSQL_HOST
              value: vworkspace-db
            - name: REDIS_HOST
              value: 'vworkspace-redis'
            - name: REDIS_HOST_PORT
              value: '6379'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: vworkspace-data
              mountPath: /var/www/html/data
            - name: vworkspace-custom-app
              mountPath: /var/www/html/custom_apps
            - name: vworkspace-config
              mountPath: /var/www/html/config
            - name: vworkspace-theme
              mountPath: /var/www/html/themes
      volumes:
        - name: vworkspace-data
          persistentVolumeClaim: 
            claimName: vworkspace-data

        - name: vworkspace-custom-app
          persistentVolumeClaim: 
            claimName: vworkspace-custom-app

        - name: vworkspace-config
          persistentVolumeClaim: 
            claimName: vworkspace-config
            
        - name: vworkspace-theme
          persistentVolumeClaim: 
            claimName: vworkspace-theme
